[env:xiaoblesense]
platform = https://github.com/maxgerhardt/platform-nordicnrf52.git
board = xiaoble
framework = arduino

lib_deps =
    arduino-libraries/ArduinoBLE
    arduino-libraries/SD

monitor_speed = 115200
upload_protocol = nrfutil
